DROP DATABASE LEISURE


CREATE DATABASE LEISURE
GO

USE LEISURE
GO

CREATE TABLE ENDERECO (
ID INT PRIMARY KEY IDENTITY,
ESTADO CHAR(2) NOT NULL,
CIDADE VARCHAR(50) NOT NULL, 
CEP CHAR(8) NOT NULL,
RUA VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL
)
GO


CREATE TABLE USUARIO (
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(50),
DATA DATE,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
SENHA VARCHAR(30) NOT NULL,
TELEFONE CHAR(11),
CPF CHAR (11) NOT NULL UNIQUE,
ATIVO BIT,
CEP_ENDERECO CHAR(8),
NUM_RESIDENCIA SMALLINT,
COMPLEMENTO VARCHAR(30)
)
GO

select * from usuario


