CREATE DATABASE LEISURE
GO

USE LEISURE
GO

CREATE TABLE ENDERECO (
ID INT PRIMARY KEY IDENTITY,
ESTADO CHAR(2) NOT NULL,
CIDADE VARCHAR(50) NOT NULL, 
CEP CHAR(8) NOT NULL,
RUA VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL
)
GO


CREATE TABLE USUARIO (
ID INT PRIMARY KEY IDENTITY,
ID_ENDERECO INT NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
SENHA VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
)
GO


